#!/bin/sh
# The chat laws' mechanical voice (row 141, SPEC INV-28/INV-35 delivery): wired as a
# UserPromptSubmit hook beside the clock's, it reminds every window of the language,
# narration, no-scissors, and routing laws (rows 249/253) — the skills and the personal
# profile stay the laws' homes, this line only reminds.
# Repo home: scripts/chat-law-hook.sh; installed copy: ~/.claude/hooks/.
echo 'Chat laws (live-spec): plain product words do the talking — internal codes (INV-x, EX-x, M-x, row numbers) and coined doc metaphors never lead a sentence to the human; they may only trail in parentheses as quiet anchors. Narrate while working: each beat names which wish is in hand and which pipeline station it stands at; a finished station gets a two-three sentence digest of what it produced; silence past ~10 minutes owes a line naming what grinds.'
echo 'No calques (live-spec): in Russian chat never loan-translate an English pack term or coined metaphor — say the industry-standard word (требование, компонент, критерий приёмки) or the plain mechanism; internal coinages live in the docs only, and anything SHOWN to the human passes the register lint first (scripts/preshow-register-lint.py).'
echo 'Say what a thing IS (live-spec): name each thing by its own positive sentence; the contrast frame — an em-dash or comma leading into a denied neighbour («X, а не Y», "X — not Y") — is banned in every text: chat, docs, artifacts, product copy. A boundary that needs naming gets its own plain sentence. The law lives in the personal profile (language.no-scissors).'
echo 'Routing (live-spec): the orchestrator seat — whatever model leads — orchestrates, briefs, and accepts; the work itself routes to the cheapest sufficient tier (opus for judgment-flavoured drafts and reviews, sonnet for mechanical multi-step, haiku for one-shots); workers locate their own anchors so the orchestrator context stays lean; a read done to understand or design past a glance is dispatched to a reader worker and the lead reads the distillation, while a read to verify or decide stays with the lead. Homes: base rule 5 + the routing rule (SPEC INV-69), base rule 25 (the reading discipline, SPEC INV-137).'
