#!/usr/bin/env python3
"""convert.py — mechanically convert TEST_MATRIX.md to the format-family member (row 477, PROTOTYPE).

Content preservation is the law: fact sentences stay VERBATIM; the conversion moves FORM only. Each
six-cell row (id · fact · spec-ref · level · owning · status) becomes five cells:
    id · fact sentence with the spec-ref appended as ONE trailing bracket · level · owning · *status*
Node-block headings stay. The preamble is replaced with the family's short preamble. The
`## Coverage validation` section retires (its checks now live in the gates). A `## Reference` section
is appended, generated by scripts/build-matrix-reference.py (run via subprocess, never hand-written).

Run from the repo root: python3 prototype/2026-07-23-matrix-format/convert.py
It rewrites TEST_MATRIX.md in place.
"""
import os
import re
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
MATRIX = os.path.join(ROOT, "TEST_MATRIX.md")
BUILDER = os.path.join(ROOT, "scripts", "build-matrix-reference.py")

INVENTORY_HEAD = "## Artifact inventory"
MATRIX_ROWS_HEAD = "## Matrix rows"
COVERAGE_HEAD = "## Coverage validation"

CANONICAL_HEADER = "| ID | Fact (from spec) | Test level | Owning test | Status |"
SEPARATOR_5 = "|---|---|---|---|---|"

NEW_PREAMBLE = """# live-spec — Test Matrix

Derived from PRODUCT_SPEC.md through the proven ARCHITECTURE.md. The package version has one home, the
VERSION file, never pinned here where it would read stale. Last reconciled with the spec: 2026-07-23.
This is the test-matrix member of the format family, written in the requirements genre the family
defines; the shared laws live once in `docs/spec-format.md` and the matrix's own additions in
`docs/test-matrix-format.md`, both inherited here by reference.

**What this document covers.** For each fact the spec states, which test holds it, pinned at which
level, and whether that test exists yet. Three parts follow: the artifact inventory (every file the
reader receives, each asserted at the rendered level), the matrix rows grouped into node blocks, and
the generated `## Reference` mapping each spec anchor to the rows that cover it.

**The bracket codes.** A code anchor — `[INV-x]`, `[T-x]`, `[E-x]`, `[M-x]` — trails at the end of a
row's fact sentence and points to the rule's home in PRODUCT_SPEC.md; the anchor is the row's parent
fact, and the generated Reference reads each row's coverage from it. A reader can ignore the anchors; a
maintainer follows them.

**How the keywords read.** The keywords *when*, *while*, *if*, *then*, and *shall* are set in lowercase
italics, and no word stands in all capitals outside a code anchor.

**Test levels, adapted to a text product.** live-spec ships documents and skills, no browser surface,
so almost every row sits at `string` — a `string` assertion against the shipped file on disk, never a
source fragment or a memory of it. The ladder's real-engine rung (`browser-computed`) is filled for
this project by a real `git` process driven against a throwaway two-worktree repo, and the rows needing
it say so (M-374, M-375, M-377, M-379, M-380). The ladder is kind-abstract, and each project fills its
rungs with its own concrete proofs.

**Status vocabulary.** *built* (the test exists and runs green) · *todo* (the owner named in the row) ·
*retired* (the row is kept, never deleted).

---

"""

REFERENCE_INTRO = (
    "The anchor-to-row table below is generated output, built from the body rows by "
    "`scripts/build-matrix-reference.py`; no one edits it by hand. Each spec anchor a body row carries "
    "maps to the matrix rows that cover it, ranges and compound anchors expanded."
)

SEP_CELL = re.compile(r"^:?-+:?$")


def convert_matrix_rows(section):
    """Convert the tables inside the `## Matrix rows` region: narrow every six-cell header/separator to
    five columns and every data row to the five-cell shape; leave node headings, blanks, and rules."""
    out = []
    for line in section.splitlines():
        if line.startswith("|"):
            cells = [c.strip() for c in line.strip("|").split("|")]
            if len(cells) == 6:
                if all(SEP_CELL.match(c) for c in cells):
                    out.append(SEPARATOR_5)
                    continue
                if cells[0] == "ID":
                    out.append(CANONICAL_HEADER)
                    continue
                # a data row: id · fact · spec-ref · level · owning · status
                rid, fact, ref, level, owning, status = cells
                new_fact = "%s [%s]" % (fact, ref)
                new_status = "*%s*" % status.strip().lower()
                out.append("| %s |" % " | ".join([rid, new_fact, level, owning, new_status]))
                continue
        out.append(line)
    return "\n".join(out)


def main():
    with open(MATRIX, encoding="utf-8") as f:
        text = f.read()

    inv_at = text.index(INVENTORY_HEAD)
    cov_at = text.index(COVERAGE_HEAD)
    middle = text[inv_at:cov_at]  # inventory + matrix rows + the trailing --- before coverage

    rows_at = middle.index(MATRIX_ROWS_HEAD)
    before_rows = middle[:rows_at]          # the artifact inventory, kept verbatim
    rows_region = middle[rows_at:]          # the matrix rows, converted
    converted_middle = before_rows + convert_matrix_rows(rows_region)

    # First write the converted body (no Reference yet), then generate the Reference from it.
    body_text = NEW_PREAMBLE + converted_middle
    if not body_text.endswith("\n"):
        body_text += "\n"
    with open(MATRIX, "w", encoding="utf-8") as f:
        f.write(body_text)

    built = subprocess.run(["python3", BUILDER, MATRIX], capture_output=True, text=True)
    if built.returncode != 0:
        sys.stderr.write("builder failed:\n%s\n%s\n" % (built.stdout, built.stderr))
        return 1
    table = built.stdout

    reference = "## Reference\n\n%s\n\n%s" % (REFERENCE_INTRO, table)
    with open(MATRIX, "w", encoding="utf-8") as f:
        f.write(body_text + reference)

    print("convert: TEST_MATRIX.md converted; Reference has %d anchor rows."
          % sum(1 for l in table.splitlines() if l.startswith("| ") and "Anchor" not in l and "---" not in l))
    return 0


if __name__ == "__main__":
    sys.exit(main())
